var annotated_dup =
[
    [ "GE", null, [
      [ "InstrumentorUtils", null, [
        [ "ChangeResult", "struct_g_e_1_1_instrumentor_utils_1_1_change_result.html", "struct_g_e_1_1_instrumentor_utils_1_1_change_result" ]
      ] ],
      [ "Camera", "class_g_e_1_1_camera.html", "class_g_e_1_1_camera" ],
      [ "EditorCamera", "class_g_e_1_1_editor_camera.html", "class_g_e_1_1_editor_camera" ],
      [ "OrthographicCamera", "class_g_e_1_1_orthographic_camera.html", "class_g_e_1_1_orthographic_camera" ],
      [ "OrthographicCameraBounds", "struct_g_e_1_1_orthographic_camera_bounds.html", "struct_g_e_1_1_orthographic_camera_bounds" ],
      [ "OrthographicCameraController", "class_g_e_1_1_orthographic_camera_controller.html", "class_g_e_1_1_orthographic_camera_controller" ],
      [ "SceneCamera", "class_g_e_1_1_scene_camera.html", "class_g_e_1_1_scene_camera" ],
      [ "ProfileResult", "struct_g_e_1_1_profile_result.html", "struct_g_e_1_1_profile_result" ],
      [ "InstrumentationSession", "struct_g_e_1_1_instrumentation_session.html", "struct_g_e_1_1_instrumentation_session" ],
      [ "Instrumentor", "class_g_e_1_1_instrumentor.html", "class_g_e_1_1_instrumentor" ],
      [ "InstrumentationTimer", "class_g_e_1_1_instrumentation_timer.html", "class_g_e_1_1_instrumentation_timer" ],
      [ "WindowResizeEvent", "class_g_e_1_1_window_resize_event.html", "class_g_e_1_1_window_resize_event" ],
      [ "WindowCloseEvent", "class_g_e_1_1_window_close_event.html", "class_g_e_1_1_window_close_event" ],
      [ "AppTickEvent", "class_g_e_1_1_app_tick_event.html", "class_g_e_1_1_app_tick_event" ],
      [ "AppUpdateEvent", "class_g_e_1_1_app_update_event.html", "class_g_e_1_1_app_update_event" ],
      [ "AppRenderEvent", "class_g_e_1_1_app_render_event.html", "class_g_e_1_1_app_render_event" ],
      [ "Event", "class_g_e_1_1_event.html", "class_g_e_1_1_event" ],
      [ "EventDispatcher", "class_g_e_1_1_event_dispatcher.html", "class_g_e_1_1_event_dispatcher" ],
      [ "KeyEvent", "class_g_e_1_1_key_event.html", "class_g_e_1_1_key_event" ],
      [ "KeyPressedEvent", "class_g_e_1_1_key_pressed_event.html", "class_g_e_1_1_key_pressed_event" ],
      [ "KeyReleasedEvent", "class_g_e_1_1_key_released_event.html", "class_g_e_1_1_key_released_event" ],
      [ "KeyTypedEvent", "class_g_e_1_1_key_typed_event.html", "class_g_e_1_1_key_typed_event" ],
      [ "MouseMovedEvent", "class_g_e_1_1_mouse_moved_event.html", "class_g_e_1_1_mouse_moved_event" ],
      [ "MouseScrolledEvent", "class_g_e_1_1_mouse_scrolled_event.html", "class_g_e_1_1_mouse_scrolled_event" ],
      [ "MouseButtonEvent", "class_g_e_1_1_mouse_button_event.html", "class_g_e_1_1_mouse_button_event" ],
      [ "MouseButtonPressedEvent", "class_g_e_1_1_mouse_button_pressed_event.html", "class_g_e_1_1_mouse_button_pressed_event" ],
      [ "MouseButtonReleasedEvent", "class_g_e_1_1_mouse_button_released_event.html", "class_g_e_1_1_mouse_button_released_event" ],
      [ "ImGuiLayer", "class_g_e_1_1_im_gui_layer.html", "class_g_e_1_1_im_gui_layer" ],
      [ "Application", "class_g_e_1_1_application.html", "class_g_e_1_1_application" ],
      [ "Input", "class_g_e_1_1_input.html", "class_g_e_1_1_input" ],
      [ "Layer", "class_g_e_1_1_layer.html", "class_g_e_1_1_layer" ],
      [ "LayerStack", "class_g_e_1_1_layer_stack.html", "class_g_e_1_1_layer_stack" ],
      [ "Log", "class_g_e_1_1_log.html", "class_g_e_1_1_log" ],
      [ "Timestep", "class_g_e_1_1_timestep.html", "class_g_e_1_1_timestep" ],
      [ "OpenGLVertexBuffer", "class_g_e_1_1_open_g_l_vertex_buffer.html", "class_g_e_1_1_open_g_l_vertex_buffer" ],
      [ "OpenGLIndexBuffer", "class_g_e_1_1_open_g_l_index_buffer.html", "class_g_e_1_1_open_g_l_index_buffer" ],
      [ "OpenGLContext", "class_g_e_1_1_open_g_l_context.html", "class_g_e_1_1_open_g_l_context" ],
      [ "OpenGLFramebuffer", "class_g_e_1_1_open_g_l_framebuffer.html", "class_g_e_1_1_open_g_l_framebuffer" ],
      [ "OpenGLRendererAPI", "class_g_e_1_1_open_g_l_renderer_a_p_i.html", "class_g_e_1_1_open_g_l_renderer_a_p_i" ],
      [ "OpenGLShader", "class_g_e_1_1_open_g_l_shader.html", "class_g_e_1_1_open_g_l_shader" ],
      [ "OpenGLTexture2D", "class_g_e_1_1_open_g_l_texture2_d.html", "class_g_e_1_1_open_g_l_texture2_d" ],
      [ "OpenGLVertexArray", "class_g_e_1_1_open_g_l_vertex_array.html", "class_g_e_1_1_open_g_l_vertex_array" ],
      [ "FileDialogs", "class_g_e_1_1_file_dialogs.html", "class_g_e_1_1_file_dialogs" ],
      [ "WindowsWindow", "class_g_e_1_1_windows_window.html", "class_g_e_1_1_windows_window" ],
      [ "BufferElement", "struct_g_e_1_1_buffer_element.html", "struct_g_e_1_1_buffer_element" ],
      [ "BufferLayout", "class_g_e_1_1_buffer_layout.html", "class_g_e_1_1_buffer_layout" ],
      [ "VertexBuffer", "class_g_e_1_1_vertex_buffer.html", "class_g_e_1_1_vertex_buffer" ],
      [ "IndexBuffer", "class_g_e_1_1_index_buffer.html", "class_g_e_1_1_index_buffer" ],
      [ "FramebufferTextureSpecification", "struct_g_e_1_1_framebuffer_texture_specification.html", "struct_g_e_1_1_framebuffer_texture_specification" ],
      [ "FramebufferAttachmentSpecification", "struct_g_e_1_1_framebuffer_attachment_specification.html", "struct_g_e_1_1_framebuffer_attachment_specification" ],
      [ "FrameBufferSpecification", "struct_g_e_1_1_frame_buffer_specification.html", "struct_g_e_1_1_frame_buffer_specification" ],
      [ "FrameBuffer", "class_g_e_1_1_frame_buffer.html", "class_g_e_1_1_frame_buffer" ],
      [ "GraphicsContext", "class_g_e_1_1_graphics_context.html", "class_g_e_1_1_graphics_context" ],
      [ "LogStream", "struct_g_e_1_1_log_stream.html", "struct_g_e_1_1_log_stream" ],
      [ "Mesh", "class_g_e_1_1_mesh.html", "class_g_e_1_1_mesh" ],
      [ "RenderCommand", "class_g_e_1_1_render_command.html", "class_g_e_1_1_render_command" ],
      [ "Renderer", "class_g_e_1_1_renderer.html", "class_g_e_1_1_renderer" ],
      [ "QuadVertex", "struct_g_e_1_1_quad_vertex.html", "struct_g_e_1_1_quad_vertex" ],
      [ "Renderer2DData", "struct_g_e_1_1_renderer2_d_data.html", "struct_g_e_1_1_renderer2_d_data" ],
      [ "Renderer2D", "class_g_e_1_1_renderer2_d.html", "class_g_e_1_1_renderer2_d" ],
      [ "RendererAPI", "class_g_e_1_1_renderer_a_p_i.html", "class_g_e_1_1_renderer_a_p_i" ],
      [ "Shader", "class_g_e_1_1_shader.html", "class_g_e_1_1_shader" ],
      [ "ShaderLibrary", "class_g_e_1_1_shader_library.html", "class_g_e_1_1_shader_library" ],
      [ "SubTexture2D", "class_g_e_1_1_sub_texture2_d.html", "class_g_e_1_1_sub_texture2_d" ],
      [ "Texture", "class_g_e_1_1_texture.html", "class_g_e_1_1_texture" ],
      [ "Texture2D", "class_g_e_1_1_texture2_d.html", "class_g_e_1_1_texture2_d" ],
      [ "VertexArray", "class_g_e_1_1_vertex_array.html", "class_g_e_1_1_vertex_array" ],
      [ "TransformComponent", "struct_g_e_1_1_transform_component.html", "struct_g_e_1_1_transform_component" ],
      [ "SpriteRendererComponent", "struct_g_e_1_1_sprite_renderer_component.html", "struct_g_e_1_1_sprite_renderer_component" ],
      [ "TagComponent", "struct_g_e_1_1_tag_component.html", "struct_g_e_1_1_tag_component" ],
      [ "CameraComponent", "struct_g_e_1_1_camera_component.html", "struct_g_e_1_1_camera_component" ],
      [ "NativeScriptComponent", "struct_g_e_1_1_native_script_component.html", "struct_g_e_1_1_native_script_component" ],
      [ "Entity", "class_g_e_1_1_entity.html", "class_g_e_1_1_entity" ],
      [ "Scene", "class_g_e_1_1_scene.html", "class_g_e_1_1_scene" ],
      [ "SceneSerializer", "class_g_e_1_1_scene_serializer.html", "class_g_e_1_1_scene_serializer" ],
      [ "ScriptableEntity", "class_g_e_1_1_scriptable_entity.html", "class_g_e_1_1_scriptable_entity" ],
      [ "WindowProps", "struct_g_e_1_1_window_props.html", "struct_g_e_1_1_window_props" ],
      [ "Window", "class_g_e_1_1_window.html", "class_g_e_1_1_window" ]
    ] ],
    [ "YAML", null, [
      [ "convert< glm::vec3 >", "struct_y_a_m_l_1_1convert_3_01glm_1_1vec3_01_4.html", "struct_y_a_m_l_1_1convert_3_01glm_1_1vec3_01_4" ],
      [ "convert< glm::vec4 >", "struct_y_a_m_l_1_1convert_3_01glm_1_1vec4_01_4.html", "struct_y_a_m_l_1_1convert_3_01glm_1_1vec4_01_4" ]
    ] ],
    [ "GLFWgamepadstate", "struct_g_l_f_wgamepadstate.html", "struct_g_l_f_wgamepadstate" ],
    [ "GLFWgammaramp", "struct_g_l_f_wgammaramp.html", "struct_g_l_f_wgammaramp" ],
    [ "GLFWimage", "struct_g_l_f_wimage.html", "struct_g_l_f_wimage" ],
    [ "GLFWvidmode", "struct_g_l_f_wvidmode.html", "struct_g_l_f_wvidmode" ]
];